import { Navbar } from "../components/Navbar";
import { CourseProvider } from "../context/CoursesContext";
import { Toaster } from "react-hot-toast";
import { Layout } from "../components/Layout";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LearnDotCOde | Administrador",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CourseProvider>
          <Navbar />
          {children}
          <Toaster />
        </CourseProvider>
      </body>
    </html>
  );
}
